[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_FIREBASE_API_KEY = "your-production-api-key"
  VITE_FIREBASE_AUTH_DOMAIN = "your-production-auth-domain"
  VITE_FIREBASE_DATABASE_URL = "your-production-database-url"
  VITE_FIREBASE_PROJECT_ID = "your-production-project-id"
  VITE_FIREBASE_STORAGE_BUCKET = "your-production-storage-bucket"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "your-production-messaging-sender-id"
  VITE_FIREBASE_APP_ID = "your-production-app-id"
